import Images from "./assets/exportAssets";
export const dataOfUsers = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 2000,
  },
  {
    name: "Apr",
    "Active User": 2780,
  },
  {
    name: "May",
    "Active User": 1890,
  },
  {
    name: "Jun",
    "Active User": 3290,
  },
  {
    name: "Jul",
    "Active User": 6490,
  },
  {
    name: "Aug",
    "Active User": 2490,
  },
  {
    name: "Sept",
    "Active User": 4490,
  },
  {
    name: "Oct",
    "Active User": 1490,
  },
  {
    name: "Nov",
    "Active User": 2490,
  },
  {
    name: "Dec",
    "Active User": 7490,
  },
];
export const productData = [
  {
    name: "Jan",
    sales: 4000,
  },
  {
    name: "Feb",
    sales: 3000,
  },
  {
    name: "Mar",
    sales: 2000,
  },
];
export const userRows = [
  {
    id: 1,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 2,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 3,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 4,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 5,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 6,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 7,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 8,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 9,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
  {
    id: 10,
    username: "Jon Snow",
    avatar: Images.user1,
    email: "snow@getMaxListeners.com",
    status: "active",
    transaction: "120pln",
  },
];
export const productRows = [
  {
    id: 1,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 2,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 3,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 4,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 5,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 6,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 7,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 8,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 9,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
  {
    id: 10,
    name: "Blender",
    img: Images.blender,
    stock: 120,
    status: "active",
    price: "120pln",
  },
];
